### ISSUE TITLE
web browser connection

### ISSUE THREAD

**Issue by danielstock** [SeppPenner/MQTTnet.TestApp.SimpleServer#1]
it works well when i connect to server with mqtt.fx client.
but it does not work when the browser tries to connect with websocket protocol.
how to solve the problem, thanks.

**Comment by SeppPenner** [comment]
That's true. The project is just a simple MQTT example and doesn't support websockets.

Maybe take a look at https://github.com/chkr1011/MQTTnet/issues/716 as well.

**Comment by danielstock** [comment]
@SeppPenner   thanks.
but i heard mqttnet.server 3.0.11  supports js connection now.
